# Generated by Django 6.0.1 on 2026-02-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
    ]
