# Generated by Django 6.0.1 on 2026-02-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
