# Generated by Django 5.2.11 on 2026-02-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_customer_alter_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Employee Management',
                'verbose_name_plural': 'Employee Management',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Invoice System',
                'verbose_name_plural': 'Invoice System',
                'managed': False,
            },
        ),
    ]
